### ISSUE TITLE
Diverging History

### ISSUE THREAD

**Issue by baffo32** [OpenBCI/OpenBCI_RFduino#2]
It looks like this repository is a fork of https://github.com/RFduino/RFduino .

The history of the source repository should be included so that fixes and improvements can be moved between the two projects.

Ideally, any changes made by OpenBCI would be done in a general manner and contributed to the origin repository ("upstream") as pull requests.  As can be seen at https://github.com/RFduino/RFduino/pulls?q=is%3Apr+is%3Aclosed , RFduino tends to merge pull requests.

**Comment by petewall** [comment]
It would be nice to know if this repository has any notable changes from the official RFduino repo.  I'm trying to reprogram the Cyton dongle, and the instructions to add a board to Arduino on [this page](http://docs.openbci.com/Hardware/06-Cyton_Radios_Programming_Tutorial#cyton-radios-programming-tutorial-uploading-device-firmware-to-cyton-board) are pretty out of date.  I'd like to know if I have to use this repo, or if I can use http://rfduino.com/package_rfduino_index.json which can be installed through the Arduino's board manager.

**Comment by biomurph** [comment]
You have to use this repository.
The folks at RFduino did some custom work for us to increase the transmission speed of the Gazelle library, and they also gave us the ability to use up to 25 discreet channels in the Gazelle library.
The only drawback is that you have to use the Arduino 1.5.8 IDE. This custom spin won't work with later versions of Arduino.
